[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 3

[profile.deploy]
gas_price = 3000000000  # 3 gwei
gas_limit = 30000000
priority_fee = 100000000  # 0.1 gwei priority fee
block_base_fee_per_gas = 1000000000  # 1 gwei
no_storage_caching = true
ffi = true
sender = "0x8660aD527b3Df16B236307e7FbE6AfFb1EE4491A"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

# RPC endpoints
[rpc_endpoints]
sepolia = "${ALCHEMY_SEPOLIA_URL}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"

# Etherscan API keys for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Test settings
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = "0x1234"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Coverage settings
[profile.coverage]
reporters = ["text", "html"]
exclude = ["test/", "script/"]

